export interface ITile {
  id: number;
  title: string;
  background: string;
  value: number;
  imgs: number;
}

let i = 0; //do not touch

export const tileData: { 85: ITile[]; 71: ITile[] } = {
  71: [
    {
      id: ++i,
      title: "3D20-7",
      background: "tiles/1.jpg",
      imgs: 4,
      value: 100,
    },
    {
      id: ++i,
      title: "3D204",
      background: "tiles/2.jpg",
      imgs: 3,
      value: 100,
    },
    {
      id: ++i,
      title: "3D303",
      background: "tiles/3.jpg",
      imgs: 3,
      value: 100,
    },
    {
      id: ++i,
      title: "5323-2",
      background: "tiles/4.jpg",
      imgs: 2,
      value: 100,
    },
    {
      id: ++i,
      title: "6413-5",
      background: "tiles/5.jpg",
      imgs: 2,
      value: 100,
    },
    {
      id: ++i,
      title: "6422",
      background: "tiles/6.jpg",
      imgs: 2,
      value: 100,
    },
    {
      id: ++i,
      title: "6441",
      background: "tiles/7.jpg",
      imgs: 2,
      value: 100,
    },
    {
      id: ++i,
      title: "6472-2",
      background: "tiles/8.jpg",
      imgs: 2,
      value: 100,
    },
    {
      id: ++i,
      title: "BMS 36413-5",
      background: "tiles/9.jpg",
      imgs: 2,
      value: 100,
    },
    {
      id: ++i,
      title: "BMS 36421",
      background: "tiles/10.jpg",
      imgs: 3,
      value: 100,
    },
    {
      id: ++i,
      title: "BMS 36471",
      background: "tiles/11.jpg",
      imgs: 3,
      value: 100,
    },
    {
      id: ++i,
      title: "BMS 36472",
      background: "tiles/12.jpg",
      imgs: 2,
      value: 100,
    },
    {
      id: ++i,
      title: "HM36423",
      background: "tiles/13.jpg",
      imgs: 2,
      value: 100,
    },
    {
      id: ++i,
      title: "M36413-7",
      background: "tiles/14.jpg",
      imgs: 2,
      value: 100,
    },
    {
      id: ++i,
      title: "6442",
      background: "tiles/15.jpg",
      imgs: 3,
      value: 100,
    },
    {
      id: ++i,
      title: "BMS 36452",
      background: "tiles/16.jpg",
      imgs: 3,
      value: 100,
    },
  ],
  85: [
    {
      id: ++i,
      title: "WY016",
      background: "tiles/17.jpg",
      imgs: 3,
      value: 100,
    },
    {
      id: ++i,
      title: "001-1W",
      background: "tiles/18.jpg",
      imgs: 3,
      value: 100,
    },
    {
      id: ++i,
      title: "004L",
      background: "tiles/19.jpg",
      imgs: 1,
      value: 100,
    },
    {
      id: ++i,
      title: "006",
      background: "tiles/20.jpg",
      imgs: 1,
      value: 100,
    },
    {
      id: ++i,
      title: "008",
      background: "tiles/21.jpg",
      imgs: 1,
      value: 100,
    },
    {
      id: ++i,
      title: "010",
      background: "tiles/22.jpg",
      imgs: 1,
      value: 100,
    },
    {
      id: ++i,
      title: "012-1",
      background: "tiles/23.jpg",
      imgs: 3,
      value: 100,
    },
    {
      id: ++i,
      title: "013",
      background: "tiles/24.jpg",
      imgs: 1,
      value: 100,
    },
    {
      id: ++i,
      title: "S003Y",
      background: "tiles/25.jpg",
      imgs: 2,
      value: 100,
    },
    {
      id: ++i,
      title: "S009-2E",
      background: "tiles/26.jpg",
      imgs: 1,
      value: 100,
    },
    {
      id: ++i,
      title: "SY006",
      background: "tiles/27.jpg",
      imgs: 3,
      value: 100,
    },
    {
      id: ++i,
      title: "SY007",
      background: "tiles/28.jpg",
      imgs: 2,
      value: 100,
    },
    {
      id: ++i,
      title: "SY013",
      background: "tiles/29.jpg",
      imgs: 1,
      value: 100,
    },
    {
      id: ++i,
      title: "WY008",
      background: "tiles/30.jpg",
      imgs: 1,
      value: 100,
    },
    {
      id: ++i,
      title: "WY016",
      background: "tiles/31.jpg",
      imgs: 2,
      value: 100,
    },
    {
      id: ++i,
      title: "Y001F",
      background: "tiles/32.jpg",
      imgs: 3,
      value: 100,
    },
    {
      id: ++i,
      title: "Y004F",
      background: "tiles/33.jpg",
      imgs: 3,
      value: 100,
    },
    {
      id: ++i,
      title: "Y007",
      background: "tiles/34.jpg",
      imgs: 3,
      value: 100,
    },
    {
      id: ++i,
      title: "YH013",
      background: "tiles/35.jpg",
      imgs: 1,
      value: 100,
    },
    {
      id: ++i,
      title: "Y005F",
      background: "tiles/36.jpg",
      imgs: 3,
      value: 100,
    },
    {
      id: ++i,
      title: "012",
      background: "tiles/37.jpg",
      imgs: 3,
      value: 100,
    },
  ],
};
